### ISSUE TITLE
cannot run browser on python 3.5.3 -- update docs

### ISSUE THREAD

**Issue by camicarballo** [wtheisen/TerminusBrowser#83]
### Issue and Steps to Reproduce
Trying to run `./TerminusBrowser.py` with python 3.5.3 gives the following error message:

```
$ ./TerminusBrowser.py Traceback (most recent call last):  File "./TerminusBrowser.py", line 14, in <module>    from Views.viewClass import View  File "src/Views/viewClass.py", line 4, in <module>    from Frames.defaultFrame import DefaultFrame  File "src/Frames/defaultFrame.py", line 9    self.footerStringRight = f''
```

### Version

Python 3.5.3

**Comment by anselmos** [comment]
The issue @camicarballo found states that source-code of TerminusBrowser is using f-strings that are introduced at python 3.6.

I've gone a step forward and created dockerfile that makes it easier to check this issue:
```
FROM python:3.5.3

RUN git clone https://github.com/wtheisen/TerminusBrowser.git
RUN cd TerminusBrowser && pip3 install -r requirements.txt
RUN cd TerminusBrowser && ./TerminusBrowser.py
```


[Dockerfile.txt](https://github.com/wtheisen/TerminusBrowser/files/3785611/Dockerfile.txt)
